name: Add hypot issues to project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

env:
  ADD_TO_PROJECT_URL: 'https://github.com/users/patricia-ternes/projects/3'

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: ${{ env.ADD_TO_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: $project_url
          github-token: ${{ env.ADD_TO_PROJECT_PAT }}
          labeled: needs-review, size/XL
          label-operator: AND
